[package]
name = "par-sieve"
version = "1.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "par_sieve"
crate-type = ["cdylib"]

[dependencies]
bitvec = "1.0.1"
pyo3 = "0.25.0"
rayon = "1.10.0"
